language: java
dist: trusty
jdk:
  - openjdk11
  - openjdk15

install:
  - mvn -N io.takari:maven:wrapper
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

branches:
  only:
    - dev

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: hr-stakeout
  on:
    branch: master

