version: '3.3'

networks:
  hrnet:
    driver: bridge
  backendnet:
    driver: bridge

volumes:
  hr_service_db: { }

services:

  hr-service-db:
    container_name: hr_service_db
    image: library/mongo:3.6.16-xenial
    env_file:
      - env/db.env
    ports:
      - 27017:27017
    restart: always
    networks:
      - hrnet

  hr-service:
    container_name: hr_service
    build: Dockerfile
    env_file:
      - env/hr.env
    ports:
      - 9090:9090
    networks:
      - hrnet
      - backendnet
    depends_on:
      - hr-service-db

