apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-db-deployment
  labels:
    apps: hr-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hr-db
  template:
    metadata:
      labels:
        app: hr-db
    spec:
      containers:
        - name: hr_db
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hr-db-secret
                  key: hr.db.username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hr-db-secret
                  key: hr.db.password
